//errors - validation
TAKE_ERROR = 1;
ILLEGAL_MOVE_ERROR = 2;
CHESS_ERROR = 3;
COLLISION_ERROR = 4;
NOT_MY_MOVE = 5;

//draw constants
DRAW_WAITING_CONFIRMATION = 1;
DRAW_DONE = 2;
DRAW_REQUEST = 3;
DRAW_ACCEPT = 4;
DRAW_REJECT = 5;